const ChartsApi = [
	{
		id: 1,
		image: "/golden-age.svg",
		title: "Golden age of 80s",
		singer: "Sean Swadder",
		duration: "2:34:45",
		link: "golden-age",
		songs: [
			{
				id: 1,
				coverArt: "/release-1.svg",
				title: "All Smoke",
				type: "Single",
				duration: "4:17",
				link: "golden-age",
				song: "/Juice_WRLD_All_Smoke.mp3",
			},
			{
				id: 2,
				coverArt: "/release-2.svg",
				title: "No Fears",
				type: "Single",
				duration: "4:17",
				link: "reggae-blues",
				song: "/Juice_WRLD_No_Fears.mp3",
			},
			{
				id: 3,
				coverArt: "/release-3.svg",
				title: "Make No Noise",
				type: "Album",
				duration: "4:17",
				link: "tomorrows-tune",
				song: "/Juice_WRLD_Make_No_Noise.mp3",
			},
			{
				id: 4,
				coverArt: "/release-4.svg",
				title: "Big Swag",
				type: "Single",
				duration: "4:17",
				link: "golden-age",
				song: "/Juice_WRLD_Big_Swag.mp3",
			},
		],
	},
	{
		id: 2,
		image: "/reggae-blues.svg",
		title: "Reggae 'n' blues",
		singer: "Dj YK mule",
		duration: "1:02:42",
		link: "reggae-blues",
		songs: [
			{
				id: 1,
				coverArt: "/release-1.svg",
				title: "Youdontloveme",
				type: "Single",
				duration: "4:17",
				link: "golden-age",
				song: "/Juice_WRLD_Youdontloveme.mp3",
			},
			{
				id: 2,
				coverArt: "/release-2.svg",
				title: "Ganga Burns",
				type: "Single",
				duration: "4:17",
				link: "reggae-blues",
				song: "/Nicki_Minaj_Ganga_Burns.mp3",
			},
			{
				id: 3,
				coverArt: "/release-3.svg",
				title: "Big Dog",
				type: "Album",
				duration: "4:17",
				link: "tomorrows-tune",
				song: "/Juice_WRLD_Big_Dog.mp3",
			},
			{
				id: 4,
				coverArt: "/release-4.svg",
				title: "Percaholic",
				type: "Single",
				duration: "4:17",
				link: "golden-age",
				song: "/Juice_WRLD_Percaholic.mp3",
			},
			{
				id: 4,
				coverArt: "/release-4.svg",
				title: "Veins",
				type: "Single",
				duration: "4:17",
				link: "golden-age",
				song: "/Lil_Peep_Veins.mp3",
			},
		],
	},
	{
		id: 3,
		image: "/tomorrows-tune.svg",
		title: "Tomorrow’s tunes",
		singer: "Obi Datti",
		duration: "2:01:25",
		link: "tomorrows-tune",
		songs: [
			{
				id: 1,
				coverArt: "/release-1.svg",
				title: "Everlasting Love",
				type: "Single",
				duration: "4:17",
				link: "golden-age",
				song: "/Juice_WRLD_Evaslating_Love.mp3",
			},
			{
				id: 2,
				coverArt: "/release-2.svg",
				title: "Can't Help It",
				type: "Single",
				duration: "4:17",
				link: "reggae-blues",
				song: "/Juice_WRLD_Can't_Help_It.mp3",
			},
			{
				id: 3,
				coverArt: "/release-3.svg",
				title: "Gym Class",
				type: "Album",
				duration: "4:17",
				link: "tomorrows-tune",
				song: "/Lil_Peep_Gym_Class.mp3",
			},
			{
				id: 4,
				coverArt: "/release-4.svg",
				title: "Demise",
				type: "Single",
				duration: "4:17",
				link: "golden-age",
				song: "/Juice_WRLD_Demise.mp3",
			},
		],
	},
];

export default ChartsApi;