const ChartsApi = [
	{
		id: 1,
		image: "/golden-age.svg",
		title: "Golden age of 80s",
		singer: "Sean Swadder",
		duration: "2:34:45",
		link: "golden-age",
		songs: [
			{
				id: 1,
				coverArt: "/release-1.svg",
				title: "All Smoke",
				type: "Single",
				duration: "4:17",
				link: "golden-age",
			},
			{
				id: 2,
				coverArt: "/release-2.svg",
				title: "No Fears",
				type: "Single",
				duration: "4:17",
				link: "reggae-blues",
			},
			{
				id: 3,
				coverArt: "/release-3.svg",
				title: "Make No Noise",
				type: "Album",
				duration: "4:17",
				link: "tomorrows-tune",
			},
			{
				id: 4,
				coverArt: "/release-4.svg",
				title: "Big Swag",
				type: "Single",
				duration: "4:17",
				link: "golden-age",
			},
		],
	},
	{
		id: 2,
		image: "/reggae-blues.svg",
		title: "Reggae 'n' blues",
		singer: "Dj YK mule",
		duration: "1:02:42",
		link: "reggae-blues",
		songs: [
			{
				id: 1,
				coverArt: "/release-1.svg",
				title: "Youdontloveme",
				type: "Single",
				duration: "4:17",
				link: "golden-age",
			},
			{
				id: 2,
				coverArt: "/release-2.svg",
				title: "The Night Is Still Young",
				type: "Single",
				duration: "4:17",
				link: "reggae-blues",
			},
			{
				id: 3,
				coverArt: "/release-3.svg",
				title: "Big Dog",
				type: "Album",
				duration: "4:17",
				link: "tomorrows-tune",
			},
			{
				id: 4,
				coverArt: "/release-4.svg",
				title: "Percaholic",
				type: "Single",
				duration: "4:17",
				link: "golden-age",
			},
		],
	},
	{
		id: 3,
		image: "/tomorrows-tune.svg",
		title: "Tomorrow’s tunes",
		singer: "Obi Datti",
		duration: "2:01:25",
		link: "tomorrows-tune",
		songs: [
			{
				id: 1,
				coverArt: "/release-1.svg",
				title: "Everlasting Love ~ Juice WRLD",
				type: "Single",
				duration: "4:17",
				link: "golden-age",
			},
			{
				id: 2,
				coverArt: "/release-2.svg",
				title: "Can't Help It ~ Juice WRLD",
				type: "Single",
				duration: "4:17",
				link: "reggae-blues",
			},
			{
				id: 3,
				coverArt: "/release-3.svg",
				title: "Gym Class ~ Lil Peep",
				type: "Album",
				duration: "4:17",
				link: "tomorrows-tune",
			},
			{
				id: 4,
				coverArt: "/release-4.svg",
				title: "Veins ~ Lil Peep",
				type: "Single",
				duration: "4:17",
				link: "golden-age",
			},
		],
	},
];

export default ChartsApi;